name = "roomatechoresapp"
main = "src/index.js"
compatibility_date = "2024-09-23"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "roomie-rhythm-db"
database_id = "31e3332c-4cb3-434f-8b57-9d1b5c1a8f2b"
